# Generated by Django 3.0.6 on 2020-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200517_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(blank=True, max_length=128, verbose_name='Навыки'),
        ),
    ]
