# Generated by Django 3.0.6 on 2020-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200524_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=128, upload_to='', verbose_name='Логотипчик'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(blank=True, max_length=128, upload_to='', verbose_name='Картинка'),
        ),
    ]
